name: "Demo Take JSON Input"

on:
  workflow_dispatch:
    inputs:
      Name:
        description: 'Customer Name'
        required: true
      Id:
        description: 'Customer ID'
        required: true
        
jobs:

  showInputs:
    name: Show Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs from JSON
        run: |
          echo Name: ${{ github.event.inputs.Name }}
          echo Id: ${{ github.event.inputs.Id }}
